### PR TITLE
Fixed chat for login, enter key press, page refresh, styles for chat

### PR DESCRIPTION
**Pull request by mhotchkiss84**
What I did:
-Made chat page work with login
-Had to add a refresh to the page after logging out/in to get the correct user to show up in chat.
**This issue was only visible is switching users during the same session/computer**
-Added on enter press for register and login form.
-Styled chat page buttons.
-Made the logout nav link hide when the user is logged out. 

What to expect:
-When registering or logging in the user can now press the enter key on the last line instead of having to click on the button.
-When logged in the proper user will show in chat and they will be able to post, edit, and delete their messages.
-When the user logs out the logout nav link disappears

Note:
This should have been multiple branches but I did one single one for the sake of time and trying to merge multiple times.

### CODE REVIEW

**Review by dylbyl — APPROVED** [review]
The only problem I see:
After registering a new user, account log-in stops working

Tested:
-Logging in and registering by pressing Enter
-Posting a chat message
-Editing and deleting a chat message

Looks good, ready to merge

**Review by swathi862 — APPROVED** [review]
Tested:
- Enter key on login and register 👍 
- Adding/Editing/Deleting messages on chat page with appropriate login and user profile 👍 
- logout link disappears while userId is null, appears when logged in 👍 

Bugs:
- Login to new/any account after registering

**Review by swathi862 — APPROVED** [review]
👍

**Review by barrygriffith84 — APPROVED** [review]
Looks great, works.  Approved to merge.

**Pull request merged**
